name: Reusable workflow

on:
  push:
    branches: [ "main" ]

  workflow_call:
    inputs:
      app_path:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
    
      - name: Run a simple javascript file
        run: node ../apps/${{ inputs.app_path }}/index.js
